AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notify-quilt-index

  Sample SAM Template for notify-quilt-index

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Events:
        NotifyQuiltIndex:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 * * ? *)
      Environment:
        Variables:
          LINE_NOTIFY_API_KEY: !Ref LineNotifyApiKey
  NotifyRealQuiltIndexFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: notify_real_quilt_index.lambda_handler
      Runtime: ruby2.5
      Events:
        NotifyQuiltIndex:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 * * ? *)
      Environment:
        Variables:
          LINE_NOTIFY_API_KEY: !Ref LineNotifyApiKey
          MACKEREL_API_KEY: !Ref MackerelApiKey

Parameters:
  LineNotifyApiKey:
    Type: String
  MackerelApiKey:
    Type: String
